# run: conda env create --file environment.yml
name: hc-tcg-bot
dependencies:
- python>=3.10
- anaconda
- aiohttp
- pip
- pip:
  - matplotlib
  - discord-py-interactions
  - apscheduler
  - pyGithub
  - pillow
  - pyjson5