[lint]
select = ["E", "W", "I", "N", "UP", "NPY", "RUF", "FIX", "ANN", "S", "BLE", "FBT", "B", "A", "C4", "DTZ", "EM", "ICN", "PIE", "Q", "ARG", "D"]

ignore = ["D211", "D213", "D413"]

unfixable = []

[format]
skip-magic-trailing-comma = true
line-ending = "cr-lf"
quote-style = "double"

[lint.isort]
split-on-trailing-comma = false
