name: Black

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: '--check'
          src: './'
          version: '22.3.0'
